version: "3.3"
services:
  web:
    build: ./
    ports:
      - "9990:80"
      - "9993:443"
    volumes:
      - ./prestashop:/var/www/html
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
