version: "2"

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    enviroment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      
  prestashop:
    build: ./prestashop_docker
    ports:
      - 80:80
    links:
      - db:db
    depends_on:
      - db
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=db
      - DB_USER=admin
      - DB_PASSWD=admin
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=0
